'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Project={id:string;title:string;description:string|null;budget_min:number|null;budget_max:number|null}
export default function ProposalsPage(){
 const router=useRouter();const params=useSearchParams();const projectId=params.get('project')||'';const [project,setProject]=useState<Project|null>(null);const [coverLetter,setCoverLetter]=useState('');const [bidAmount,setBidAmount]=useState('');const [deliveryDays,setDeliveryDays]=useState('5');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
 useEffect(()=>{let mounted=true;async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}if(!mounted)return;if(!projectId){setError('No project selected.');setLoading(false);return}const {data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).single();if(!mounted)return;if(profile?.role!=='freelancer'&&profile?.role!=='admin'){setError('Only freelancers can submit proposals.');setLoading(false);return}const {data,error:e}=await supabase.from('projects').select('id,title,description,budget_min,budget_max').eq('id',projectId).single();if(!mounted)return;if(e)setError(e.message);else{setProject(data);setBidAmount(String(data?.budget_max??data?.budget_min??''))}setLoading(false)}load();return()=>{mounted=false}},[projectId,router])
 async function submit(e:FormEvent){e.preventDefault();if(saving)return;setSaving(true);setError('');setMessage('');const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');setSaving(false);return}const letter=coverLetter.trim();const amount=Number(bidAmount);const days=Number(deliveryDays);if(letter.length<20||!Number.isFinite(amount)||!Number.isInteger(amount)||amount<=0||!Number.isInteger(days)||days<1||days>365){setError('Proposal must be at least 20 characters, bid must be a positive whole PKR amount, and delivery must be 1–365 days.');setSaving(false);return}const {error:e2}=await supabase.from('proposals').insert({project_id:projectId,freelancer_id:user.id,cover_letter:letter,bid_amount:amount,delivery_days:days});if(e2)setError(e2.code==='23505'?'You have already submitted a proposal for this project.':e2.message);else{setMessage('Proposal submitted successfully. The client can now review your bid.');setCoverLetter('')}setSaving(false)}
 if(loading)return <main className="section"><div className="container"><div className="card" role="status"><p>Loading project...</p></div></div></main>
 if(!project)return <main className="section"><div className="container"><div className="card"><h2>Unable to submit proposal</h2><p className="muted">{error}</p><Link className="btn" href="/work">Back to projects</Link></div></div></main>
 const budgetLabel=project.budget_min!=null||project.budget_max!=null?`PKR ${Number(project.budget_min??0).toLocaleString()}–${Number(project.budget_max??project.budget_min??0).toLocaleString()}`:'Budget negotiable'
 return <main className="section"><div className="container"><div className="sectionHeader" style={{alignItems:'start',gap:16}}><div style={{minWidth:0}}><span className="pill">Submit proposal</span><h1 style={{overflowWrap:'anywhere'}}>{project.title}</h1><p className="muted" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{project.description||'No project description provided.'}</p><p><b>Budget:</b> {budgetLabel}</p></div><Link href={`/project/${project.id}`} className="btn">Back to project</Link></div><form className="card" style={{maxWidth:760,marginTop:28}} onSubmit={submit} aria-busy={saving}><h2>Make your offer</h2><p className="muted">Show the client what you can deliver, how you will approach the work, and when you can finish.</p><div className="field"><label htmlFor="proposal">Your proposal</label><textarea id="proposal" rows={8} value={coverLetter} onChange={e=>setCoverLetter(e.target.value)} placeholder="Explain your experience, approach and why you are a good fit..." required minLength={20} maxLength={3000} aria-describedby="proposal-count"/><p id="proposal-count" className="muted" aria-live="polite">{coverLetter.length}/3000 characters</p></div><div className="grid"><div className="field"><label htmlFor="bid">Your bid (PKR)</label><input id="bid" type="number" min="1" step="1" value={bidAmount} onChange={e=>setBidAmount(e.target.value)} placeholder="e.g. 25000" required /></div><div className="field"><label htmlFor="days">Delivery time (days)</label><input id="days" type="number" min="1" max="365" step="1" value={deliveryDays} onChange={e=>setDeliveryDays(e.target.value)} required /></div></div>{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status" aria-live="polite">{message}</p>}<button type="submit" className="btn primary" disabled={saving} aria-busy={saving}>{saving?'Submitting proposal...':'Submit proposal'}</button></form></div></main>
}
