'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Order={id:string;client_id:string;freelancer_id:string;service_id:string|null;project_id:string|null;amount_pkr:number;status:string;requirements:string|null;created_at:string}
type Person={full_name:string|null}
const nextForFreelancer:Record<string,string>={pending:'active',active:'in_progress',in_progress:'delivered'}

export default function OrderDetail(){
 const {id}=useParams();const router=useRouter();const orderId=String(id)
 const [order,setOrder]=useState<Order|null>(null);const [userId,setUserId]=useState('');const [other,setOther]=useState<Person|null>(null);const [alreadyReviewed,setAlreadyReviewed]=useState(false);const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');const [error,setError]=useState('');const [review,setReview]=useState('');const [rating,setRating]=useState('5');const [savingReview,setSavingReview]=useState(false);const [updating,setUpdating]=useState(false)
 useEffect(()=>{async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}setUserId(user.id);const {data:o,error:e}=await supabase.from('orders').select('id,client_id,freelancer_id,service_id,project_id,amount_pkr,status,requirements,created_at').eq('id',orderId).single();if(e||!o){setError(e?.message||'Order not found');setLoading(false);return}if(user.id!==o.client_id&&user.id!==o.freelancer_id){setError('You are not a participant in this order.');setLoading(false);return}setOrder(o);const otherId=o.client_id===user.id?o.freelancer_id:o.client_id;const [{data:p},{data:existing}]=await Promise.all([supabase.from('profiles').select('full_name').eq('id',otherId).single(),supabase.from('reviews').select('id').eq('order_id',o.id).eq('reviewer_id',user.id).maybeSingle()]);setOther(p);setAlreadyReviewed(!!existing);setLoading(false)}load()},[orderId,router])
 async function changeStatus(newStatus:string){if(!order||updating)return;setUpdating(true);setError('');setMessage('');const {error:e}=await supabase.from('orders').update({status:newStatus}).eq('id',order.id).in('status',isClientStatus(newStatus)?['delivered']:['pending','active','in_progress','revision_requested']);if(e)setError(e.message);else setOrder({...order,status:newStatus});setUpdating(false)}
 function isClientStatus(s:string){return s==='completed'||s==='revision_requested'}
 async function submitReview(e:FormEvent){e.preventDefault();if(!order||order.status!=='completed'||!review.trim()||savingReview)return;setSavingReview(true);setError('');setMessage('');const {error:e2}=await supabase.from('reviews').insert({order_id:order.id,reviewer_id:userId,reviewee_id:order.client_id===userId?order.freelancer_id:order.client_id,rating:Number(rating),body:review.trim()});if(e2)setError(e2.code==='23505'?'You have already reviewed this order.':e2.message);else{setMessage('Review submitted successfully.');setReview('');setAlreadyReviewed(true)}setSavingReview(false)}
 if(loading)return <main className="section"><div className="container"><p>Loading order...</p></div></main>
 if(!order)return <main className="section"><div className="container"><div className="card"><h2>Order not found</h2><p className="muted">{error}</p><Link className="btn" href="/orders">Back to orders</Link></div></div></main>
 const isClient=order.client_id===userId;const isFreelancer=order.freelancer_id===userId
 return <main className="section"><div className="container"><div className="sectionhead"><div><span className="pill">Order #{order.id.slice(0,8)}</span><h1>{isClient?'Your order':'Client order'}</h1><p className="muted">With {other?.full_name||'HUNAR member'} · {order.status.replaceAll('_',' ')}</p></div><Link className="btn" href="/orders">Back</Link></div><div className="grid" style={{marginTop:28}}><div className="card" style={{gridColumn:'span 2'}}><h2>Order details</h2><p><b>Amount:</b> PKR {Number(order.amount_pkr).toLocaleString()}</p><p><b>Requirements:</b></p><p className="muted">{order.requirements||'No requirements provided.'}</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:20}}><Link className="btn" href={`/messages?order=${order.id}`}>Open messages</Link>{isFreelancer&&nextForFreelancer[order.status]&&<button className="btn primary" disabled={updating} onClick={()=>changeStatus(nextForFreelancer[order.status])}>{updating?'Updating...':order.status==='pending'?'Accept order':order.status==='active'?'Start work':'Mark delivered'}</button>}{isClient&&order.status==='delivered'&&<><button className="btn primary" disabled={updating} onClick={()=>changeStatus('completed')}>Accept delivery</button><button className="btn" disabled={updating} onClick={()=>changeStatus('revision_requested')}>Request revision</button></>}{isFreelancer&&order.status==='revision_requested'&&<button className="btn primary" disabled={updating} onClick={()=>changeStatus('in_progress')}>Resume work</button>}</div></div><div className="card"><h3>Status</h3><p className="pill">{order.status.replaceAll('_',' ')}</p><p className="muted">Created {new Date(order.created_at).toLocaleString()}</p></div></div>{error&&<p role="alert" style={{marginTop:20}}>{error}</p>}{message&&<p role="status" style={{marginTop:20}}>{message}</p>}{order.status==='completed'&&!alreadyReviewed&&<form className="card" style={{maxWidth:760,marginTop:28}} onSubmit={submitReview}><h2>Leave a review</h2><div className="field"><label>Rating<select value={rating} onChange={e=>setRating(e.target.value)}><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Average</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label></div><div className="field"><label>Comment<textarea rows={4} value={review} onChange={e=>setReview(e.target.value)} placeholder="Share your experience..." required maxLength={1000}/></label></div><button className="btn primary" disabled={savingReview}>{savingReview?'Submitting...':'Submit review'}</button></form>}{order.status==='completed'&&alreadyReviewed&&<div className="card" style={{maxWidth:760,marginTop:28}}><h2>Review submitted ✓</h2><p className="muted">Thank you for reviewing this order.</p></div>}</div></main>
}
