'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Freelancer={id:string;full_name:string;username:string|null;bio:string|null;location:string|null;verified:boolean;avatar_url:string|null}
type Service={id:string;freelancer_id:string;category_id:string|null;title:string;price_pkr:number;rating:number;review_count:number;delivery_days:number}
type Category={id:string;name:string}

export default function Talent(){
 const searchParams=useSearchParams();const selectedCategory=searchParams.get('category')||'';const initialQuery=searchParams.get('q')||'';const [people,setPeople]=useState<Freelancer[]>([]);const [services,setServices]=useState<Service[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [query,setQuery]=useState(initialQuery);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{setQuery(initialQuery)},[initialQuery])
 useEffect(()=>{let mounted=true;async function load(){setLoading(true);setError('');const [{data:profiles,error:profilesError},{data:serviceRows,error:servicesError},{data:cats,error:catsError}]=await Promise.all([supabase.from('profiles').select('id,full_name,username,bio,location,verified,avatar_url').eq('role','freelancer').order('created_at',{ascending:false}),supabase.from('services').select('id,freelancer_id,category_id,title,price_pkr,rating,review_count,delivery_days').eq('published',true).order('created_at',{ascending:false}),supabase.from('categories').select('id,name').order('name')]);if(!mounted)return;if(profilesError||servicesError||catsError){setError(profilesError?.message||servicesError?.message||catsError?.message||'Unable to load talent right now.');setLoading(false);return}setPeople(profiles??[]);setServices(serviceRows??[]);setCategories(cats??[]);setLoading(false)}load();return()=>{mounted=false}},[])
 const categoryId=categories.find(c=>c.name.toLowerCase()===selectedCategory.toLowerCase())?.id
 const filtered=useMemo(()=>people.filter(p=>{const mine=services.filter(s=>s.freelancer_id===p.id);const text=`${p.full_name} ${p.bio||''} ${p.location||''} ${mine.map(s=>s.title).join(' ')}`.toLowerCase();const q=query.trim().toLowerCase();const cat=!selectedCategory||mine.some(s=>categoryId?s.category_id===categoryId:s.title.toLowerCase().includes(selectedCategory.toLowerCase()));return (!q||text.includes(q))&&cat}),[people,services,query,selectedCategory,categoryId])
 const initials=(name:string)=>name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()
 return <main className="section discovery"><div className="container"><div className="discoveryHero"><span className="pill">HUNAR Talent Network</span><h1>Find people who can <span>build the work.</span></h1><p>Explore verified Pakistani freelancers across development, design, marketing, AI, writing and more. Search skills, services or names.</p></div><form className="discoverySearch" onSubmit={e=>e.preventDefault()}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search talent, skills or services..." aria-label="Search freelancers or services"/><button className="btn primary" type="submit">Search talent ↗</button></form>{selectedCategory&&<p className="muted" style={{marginTop:14}}>Category <b>{selectedCategory}</b> · <Link href="/talent">Clear filter</Link></p>}<div className="resultMeta"><div><h2>{loading?'Discovering talent':`${filtered.length} ${filtered.length===1?'freelancer':'freelancers'}`}</h2><p className="muted">{selectedCategory?`Showing ${selectedCategory} specialists.`:'Fresh talent and published services from HUNAR.'}</p></div><Link className="btn" href="/categories">Browse categories</Link></div>{loading?<div className="card emptyState"><p className="muted">Loading talent network...</p></div>:error?<div className="card emptyState errorState" role="alert"><h3>Couldn’t load talent</h3><p className="muted">{error}</p><button className="btn primary" style={{marginTop:14}} onClick={()=>window.location.reload()}>Try again</button></div>:filtered.length===0?<div className="card emptyState"><h3>No matching freelancers</h3><p className="muted">Try another skill or clear the category filter.</p>{(query||selectedCategory)&&<Link className="btn" style={{marginTop:14}} href="/talent">Clear filters</Link>}</div>:<div className="talentGrid">{filtered.map(p=>{const mine=services.filter(x=>x.freelancer_id===p.id);const s=mine[0];return <article className="card talentCard" key={p.id}><div className="talentTop">{p.avatar_url?<div className="talentAvatar"><img src={p.avatar_url} alt={`${p.full_name} profile`}/></div>:<div className="talentAvatar" aria-hidden="true">{initials(p.full_name)}</div>}<div><h3 className="talentName">{p.full_name}</h3><p className="talentRole">{p.location||'Pakistan'} · {p.verified?'✓ Verified talent':'Independent freelancer'}</p></div></div><p className="talentBio">{p.bio||'Professional freelancer on HUNAR, ready for the next project.'}</p>{s&&<><div className="talentTags"><span>{s.title}</span><span>★ {Number(s.rating).toFixed(1)}</span><span>{s.delivery_days}d delivery</span></div><div className="talentFooter"><span className="talentPrice">Starting at <b>PKR {Number(s.price_pkr).toLocaleString()}</b></span><Link className="btn primary" href={`/checkout?service=${s.id}`}>Hire</Link></div></>}<Link className="btn" href={`/freelancer/${p.username||p.id}`} style={{marginTop:10,width:'100%'}}>View profile</Link></article>})}</div>}</div></main>
}