'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Project={id:string;title:string;description:string|null;budget_min:number|null;budget_max:number|null;deadline:string|null;created_at:string;category_id:string|null}
type Category={id:string;name:string}
export default function Work(){
 const params=useSearchParams();const category=params.get('category')||'';const [projects,setProjects]=useState<Project[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [query,setQuery]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>{let mounted=true;async function load(){const [projectsResult,categoriesResult]=await Promise.all([supabase.from('projects').select('id,title,description,budget_min,budget_max,deadline,created_at,category_id').order('created_at',{ascending:false}),supabase.from('categories').select('id,name').order('name')]);if(!mounted)return;if(projectsResult.error){setError(projectsResult.error.message)}else setProjects(projectsResult.data??[]);if(!categoriesResult.error)setCategories(categoriesResult.data??[]);setLoading(false)}load();return()=>{mounted=false}},[])
 const selectedCategory=categories.find(c=>c.id===category||c.name.toLowerCase()===category.toLowerCase());
 const filtered=useMemo(()=>projects.filter(p=>{const text=`${p.title} ${p.description||''}`.toLowerCase();const q=query.trim().toLowerCase();const matchesSearch=!q||text.includes(q);const matchesCategory=!category||(selectedCategory? p.category_id===selectedCategory.id : text.includes(category.toLowerCase().split(' & ')[0]));return matchesSearch&&matchesCategory}),[projects,query,category,selectedCategory])
 return <main className="section discovery"><div className="container"><div className="discoveryHero"><span className="pill">HUNAR Project Board</span><h1>Find work worth <span>building.</span></h1><p>Discover real client projects, understand the brief and send a proposal that gets you noticed.</p></div><div className="discoverySearch"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects, skills or keywords..." aria-label="Search projects"/><button className="btn primary" type="button">Search projects ↗</button></div>{category&&<p className="muted" style={{marginTop:14}}>Category <b>{selectedCategory?.name||category}</b> · <Link href="/work">Clear filter</Link></p>}<div className="resultMeta"><div><h2>{loading?'Loading board':`${filtered.length} ${filtered.length===1?'project':'projects'}`}</h2><p className="muted">Open opportunities from clients looking for skilled professionals.</p></div><Link href="/dashboard" className="btn">My dashboard</Link></div>{error?<div className="card emptyState errorState" role="alert"><h3>We couldn't load projects</h3><p className="muted">{error}</p></div>:loading?<div className="card emptyState" role="status"><p className="muted">Loading the project board...</p></div>:filtered.length===0?<div className="card emptyState"><h3>{projects.length?'No matching projects':'No projects available yet'}</h3><p className="muted">{projects.length?'Try another search or clear the category filter.':'New client projects will appear here when they are posted.'}</p>{projects.length>0&&<Link className="btn" href="/work" style={{marginTop:14}}>Clear filters</Link>}</div>:<div className="workGrid">{filtered.map((p,i)=><article className="card projectCard" key={p.id}><span className="projectNumber">PROJECT / {String(i+1).padStart(2,'0')}</span><h3>{p.title}</h3><p className="description">{p.description||'No description provided. Open the brief to see project details.'}</p><div className="projectInfo"><span>{p.budget_min!=null||p.budget_max!=null?`PKR ${Number(p.budget_min??0).toLocaleString()}–${Number(p.budget_max??p.budget_min??0).toLocaleString()}`:'Budget negotiable'}</span>{p.deadline&&<span>Due {new Date(p.deadline).toLocaleDateString()}</span>}<span>Open</span></div><div style={{display:'flex',gap:9,flexWrap:'wrap'}}><Link className="btn" href={`/project/${p.id}`}>View brief</Link><Link className="btn primary" href={`/proposals?project=${p.id}`}>Send proposal ↗</Link></div></article>)}</div>}</div></main>
}