'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Order={id:string;amount_pkr:number;status:string;requirements:string|null;created_at:string;service_id:string|null;client_id:string;freelancer_id:string}
type Profile={id:string;full_name:string|null}
const statuses=['all','pending','active','in_progress','delivered','revision_requested','completed','cancelled','disputed']
export default function Orders(){
 const router=useRouter();const [orders,setOrders]=useState<Order[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [loading,setLoading]=useState(true);const [userId,setUserId]=useState('');const [filter,setFilter]=useState('all');const [actionId,setActionId]=useState('')
 useEffect(()=>{async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}setUserId(user.id);const {data,error}=await supabase.from('orders').select('id,amount_pkr,status,requirements,created_at,service_id,client_id,freelancer_id').order('created_at',{ascending:false});if(!error&&data){setOrders(data);const ids=Array.from(new Set(data.flatMap(o=>[o.client_id,o.freelancer_id])));if(ids.length){const {data:people}=await supabase.from('profiles').select('id,full_name').in('id',ids);setProfiles(Object.fromEntries((people??[]).map(p=>[p.id,p])))}}setLoading(false)}load()},[router])
 async function updateStatus(id:string,status:'completed'|'in_progress'|'delivered'|'revision_requested'){setActionId(id);const {data,error}=await supabase.rpc('change_order_status',{p_order_id:id,p_status:status});if(!error&&data)setOrders(current=>current.map(o=>o.id===id?{...o,status:data}:o));setActionId('')}
 const filtered=useMemo(()=>filter==='all'?orders:orders.filter(o=>o.status===filter),[orders,filter])
 return <main className="section"><div className="container"><div className="sectionhead"><div><span className="pill">My orders</span><h1>Orders & delivery</h1><p className="muted">Track purchases, delivery progress and completed work in one place.</p></div><Link className="btn" href="/dashboard">Dashboard</Link></div><div style={{display:'flex',gap:8,flexWrap:'wrap',margin:'24px 0'}}>{statuses.map(s=><button key={s} className={`btn ${filter===s?'primary':''}`} onClick={()=>setFilter(s)}>{s.replaceAll('_',' ')}</button>)}</div>{loading?<p>Loading orders...</p>:filtered.length===0?<div className="card"><h3>{orders.length?'No orders match this filter':'No orders yet'}</h3><p className="muted">{orders.length?'Choose another status above.':'Your orders will appear here after a client places an order.'}</p>{!orders.length&&<Link className="btn primary" href="/talent">Find Talent</Link>}</div>:<div className="grid">{filtered.map(order=>{const isClient=order.client_id===userId;const otherId=isClient?order.freelancer_id:order.client_id;const busy=actionId===order.id;return <div className="card" key={order.id}><div className="sectionhead"><div><span className="pill">{order.status.replaceAll('_',' ')}</span><h3>Order #{order.id.slice(0,8)}</h3></div><b>PKR {Number(order.amount_pkr).toLocaleString()}</b></div><p className="muted">{isClient?'Freelancer':'Client'}: {profiles[otherId]?.full_name||'HUNAR member'}</p><p>{order.requirements||'No requirements added.'}</p><p className="muted">Created: {new Date(order.created_at).toLocaleDateString()}</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><Link className="btn primary" href={`/orders/${order.id}`}>Open order</Link><Link className="btn" href={`/messages?order=${order.id}`}>Messages</Link>{isClient&&order.status==='delivered'&&<><button className="btn primary" disabled={busy} onClick={()=>updateStatus(order.id,'completed')}>{busy?'Updating...':'Accept delivery'}</button><button className="btn" disabled={busy} onClick={()=>updateStatus(order.id,'revision_requested')}>Request revision</button></>}{!isClient&&order.status==='active'&&<button className="btn primary" disabled={busy} onClick={()=>updateStatus(order.id,'in_progress')}>{busy?'Updating...':'Start work'}</button>}{!isClient&&order.status==='in_progress'&&<button className="btn primary" disabled={busy} onClick={()=>updateStatus(order.id,'delivered')}>{busy?'Updating...':'Mark delivered'}</button>}</div></div>})}</div>}</div></main>
}
