'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Service={id:string;title:string;price_pkr:number;freelancer_id:string;delivery_days:number;profiles:{full_name:string|null}|null}
export default function Checkout(){const router=useRouter();const params=useSearchParams();const [service,setService]=useState<Service|null>(null);const [requirements,setRequirements]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [canOrder,setCanOrder]=useState(false)
useEffect(()=>{let mounted=true;async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const {data:profile}=await supabase.from('profiles').select('role').eq('id',user.id).single();const allowed=profile?.role==='client'||profile?.role==='admin';const id=params.get('service');if(!id){if(mounted){setCanOrder(allowed);setError('Please select a service before opening checkout.');setLoading(false)}return}const {data,error:serviceError}=await supabase.from('services').select('id,title,price_pkr,freelancer_id,delivery_days,profiles:freelancer_id(full_name)').eq('published',true).eq('id',id).maybeSingle();if(!mounted)return;setCanOrder(allowed);if(!allowed)setError('Only clients can place service orders.');if(serviceError)setError('We could not load this service. Please try again.');else if(data)setService(data as Service);else setError('This service is unavailable or has been unpublished.');setLoading(false)}load();return()=>{mounted=false}},[params,router])
async function placeOrder(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');const finalRequirements=requirements.trim();if(!canOrder){setError('Only clients can place service orders.');setSaving(false);return}if(!service){setError('Service is unavailable.');setSaving(false);return}if(finalRequirements.length<10){setError('Please provide at least 10 characters describing your requirements.');setSaving(false);return}if(finalRequirements.length>3000){setError('Requirements must be 3000 characters or less.');setSaving(false);return}const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');setSaving(false);return}const {data:orderId,error:e2}=await supabase.rpc('create_service_order',{p_service_id:service.id,p_requirements:finalRequirements});if(e2){setError(e2.message);setSaving(false);return}if(!orderId){setError('Order could not be created. Please try again.');setSaving(false);return}setMessage('Order request created successfully. Redirecting...');setRequirements('');router.push(`/orders/${orderId}`)}
if(loading)return <main className="section"><div className="container"><p className="muted" role="status">Loading checkout...</p></div></main>
if(!service)return <main className="section"><div className="container"><div className="card"><h2>Choose a service</h2><p className="muted">Checkout must be opened from a specific published service. No payment has been taken.</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:16}}><Link href="/talent" className="btn primary">Browse talent</Link><Link href="/dashboard" className="btn">Dashboard</Link></div>{error&&<p role="alert" style={{marginTop:16}}>{error}</p>}</div></div></main>
return <main className="section"><div className="container"><span className="pill">Secure checkout</span><h1>Place your HUNAR order</h1>{error&&!canOrder&&<div className="card" style={{marginTop:20}}><p role="alert">{error}</p><Link href="/dashboard" className="btn">Go to dashboard</Link></div>}<div className="grid"><form className="card" style={{gridColumn:'span 2'}} onSubmit={placeOrder} aria-busy={saving}><h2>{service.title}</h2><p>By {service.profiles?.full_name||'HUNAR freelancer'} · PKR {Number(service.price_pkr).toLocaleString()} · {service.delivery_days} day delivery</p><div className="field"><label htmlFor="requirements">Project requirements<textarea id="requirements" rows={6} maxLength={3000} value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="Describe exactly what you need, including files, content, deadline or special instructions..." required /></label><p className="muted" aria-live="polite">{requirements.length}/3000</p></div><div className="card" style={{marginTop:16}}><h3>Payment</h3><p className="muted">Payment gateway integration is coming next. For now, creating an order request does not charge you.</p><p className="muted">Available methods will include JazzCash, Easypaisa, Bank Transfer and International Card once payment processing is connected.</p></div>{error&&canOrder&&<p role="alert">{error}</p>}{message&&<p role="status" aria-live="polite">{message}</p>}<button className="btn primary" disabled={saving||!canOrder}>{saving?'Creating order...':'Create order request'}</button></form><div className="card"><h3>Order summary</h3><p>Service <b style={{float:'right'}}>PKR {Number(service.price_pkr).toLocaleString()}</b></p><p>Protection <b style={{float:'right'}}>Included</b></p><hr/><h2>PKR {Number(service.price_pkr).toLocaleString()}</h2><p className="muted">No payment is taken at this stage. Payment processing will be enabled after gateway integration.</p><Link href="/dashboard" className="btn">Dashboard</Link></div></div></div></main>}
