'use client'

import { FormEvent, useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Service = { id:string; title:string; price_pkr:number; freelancer_id:string; delivery_days:number; profiles:{full_name:string|null}|null }

export default function Checkout(){const router=useRouter();const params=useSearchParams();const [service,setService]=useState<Service|null>(null);const [requirements,setRequirements]=useState('');const [payment,setPayment]=useState('JazzCash');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('')
useEffect(()=>{async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}const id=params.get('service');let q=supabase.from('services').select('id,title,price_pkr,freelancer_id,delivery_days,profiles:freelancer_id(full_name)').eq('published',true);if(id)q=q.eq('id',id);const {data}=await q.limit(1).maybeSingle();if(data)setService(data as Service);setLoading(false)}load()},[params,router])
async function placeOrder(e:FormEvent){e.preventDefault();setSaving(true);setError('');setMessage('');const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace('/login');return}if(!service){setError('Service is unavailable.');setSaving(false);return}if(service.freelancer_id===user.id){setError('You cannot order your own service.');setSaving(false);return}const {error:e2}=await supabase.from('orders').insert({client_id:user.id,freelancer_id:service.freelancer_id,service_id:service.id,amount_pkr:Number(service.price_pkr),status:'pending',requirements:`${requirements.trim()}\nPayment method selected: ${payment}`.trim()});if(e2)setError(e2.message);else{setMessage('Order request created successfully.');setRequirements('')}setSaving(false)}
if(loading)return <main className="section"><div className="container"><p>Loading checkout...</p></div></main>
if(!service)return <main className="section"><div className="container"><div className="card"><h2>Service not found</h2><p className="muted">This service may be unpublished or unavailable.</p><Link href="/talent" className="btn primary">Browse talent</Link></div></div></main>
return <main className="section"><div className="container"><span className="pill">Secure checkout</span><h1>Place your HUNAR order</h1><div className="grid"><form className="card" style={{gridColumn:'span 2'}} onSubmit={placeOrder}><h2>{service.title}</h2><p>By {service.profiles?.full_name||'HUNAR freelancer'} · PKR {Number(service.price_pkr).toLocaleString()} · {service.delivery_days} day delivery</p><div className="field"><label>Project requirements<textarea rows={6} value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="Describe what you need..." required /></label></div><div className="field"><label>Payment method<select value={payment} onChange={e=>setPayment(e.target.value)}><option>JazzCash</option><option>Easypaisa</option><option>Bank Transfer</option><option>International Card</option></select></label></div>{error&&<p role="alert">{error}</p>}{message&&<p>{message}</p>}<button className="btn primary" disabled={saving}>{saving?'Creating order...':'Create order request'}</button></form><div className="card"><h3>Order summary</h3><p>Service <b style={{float:'right'}}>PKR {Number(service.price_pkr).toLocaleString()}</b></p><p>Protection <b style={{float:'right'}}>Included</b></p><hr/><h2>PKR {Number(service.price_pkr).toLocaleString()}</h2><p className="muted">Payment gateway can be connected after the marketplace flow is verified.</p><Link href="/dashboard" className="btn">Dashboard</Link></div></div></div></main>}
