'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Profile={full_name:string|null;role:'client'|'freelancer'|'admin'|null}
type Stats={orders:number;active:number;completed:number;services:number;projects:number}

export default function Dashboard(){
 const router=useRouter();const [profile,setProfile]=useState<Profile|null>(null);const [email,setEmail]=useState('');const [stats,setStats]=useState<Stats>({orders:0,active:0,completed:0,services:0,projects:0});const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [loggingOut,setLoggingOut]=useState(false)
 useEffect(()=>{let mounted=true;async function load(){const {data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user){router.replace('/login');return}setEmail(user.email||'');const [profileResult,ordersResult,servicesResult,projectsResult]=await Promise.all([supabase.from('profiles').select('full_name,role').eq('id',user.id).single(),supabase.from('orders').select('id,status').or(`client_id.eq.${user.id},freelancer_id.eq.${user.id}`),supabase.from('services').select('id').eq('freelancer_id',user.id),supabase.from('projects').select('id').eq('client_id',user.id)]);if(!mounted)return;if(profileResult.error){setError('We could not load your dashboard. Please refresh and try again.');setLoading(false);return}if(ordersResult.error||servicesResult.error||projectsResult.error){setError('Some dashboard statistics could not be loaded. Please refresh and try again.')}const rows=ordersResult.data??[];setProfile(profileResult.data);setStats({orders:rows.length,active:rows.filter(x=>['pending','active','in_progress','delivered','revision_requested'].includes(x.status)).length,completed:rows.filter(x=>x.status==='completed').length,services:(servicesResult.data??[]).length,projects:(projectsResult.data??[]).length});setLoading(false)}load();return()=>{mounted=false}},[router])
 async function logout(){setLoggingOut(true);setError('');const {error:logoutError}=await supabase.auth.signOut();if(logoutError){setError('Could not log out. Please try again.');setLoggingOut(false);return}router.replace('/');router.refresh()}
 if(loading)return <main className="section"><div className="container"><p className="muted" role="status">Loading your dashboard...</p></div></main>
 const role=profile?.role||'client';const freelancer=role==='freelancer'||role==='admin'
 return <main className="section"><div className="container"><div className="sectionhead"><div><span className="pill">HUNAR dashboard</span><h1>Welcome{profile?.full_name?`, ${profile.full_name}`:''}.</h1><p className="muted">{email} · {role}</p></div><button className="btn" onClick={logout} disabled={loggingOut}>{loggingOut?'Logging out...':'Log out'}</button></div>{error&&<p role="alert" style={{marginTop:16}}>{error}</p>}<div className="grid" style={{marginTop:28}}><div className="card"><span className="muted">Total orders</span><h2>{stats.orders}</h2></div><div className="card"><span className="muted">Active orders</span><h2>{stats.active}</h2></div><div className="card"><span className="muted">Completed</span><h2>{stats.completed}</h2></div>{freelancer?<div className="card"><span className="muted">Published services</span><h2>{stats.services}</h2></div>:<div className="card"><span className="muted">My projects</span><h2>{stats.projects}</h2></div>}</div><div className="grid" style={{marginTop:20}}><Link className="card" href="/profile"><h3>My Profile</h3><p className="muted">Update your name, username, bio and location.</p></Link><Link className="card" href="/orders"><h3>My Orders</h3><p className="muted">Track orders, delivery, revisions and messages.</p></Link><Link className="card" href="/messages"><h3>Messages</h3><p className="muted">Communicate with clients and freelancers.</p></Link>{freelancer?<Link className="card" href="/freelancer/new-service"><h3>Create a Service</h3><p className="muted">Publish a professional service and start receiving orders.</p></Link>:<Link className="card" href="/project/new"><h3>Post a Project</h3><p className="muted">Tell freelancers what you need and set your budget.</p></Link>}<Link className="card" href="/talent"><h3>Find Talent</h3><p className="muted">Discover skilled Pakistani freelancers.</p></Link><Link className="card" href="/work"><h3>Find Work</h3><p className="muted">Explore client projects and freelance opportunities.</p></Link><Link className="card" href="/categories"><h3>Browse Categories</h3><p className="muted">Explore services by skill and category.</p></Link></div></div></main>
}