'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Project = { id: string; client_id: string; title: string; description: string | null; budget_min: number | null; budget_max: number | null; deadline: string | null }
type Proposal = { id: string; freelancer_id: string; cover_letter: string; bid_amount: number; delivery_days: number; status: string; created_at: string; profile?: { full_name: string | null } | null }

export default function ProjectDetails() {
  const params = useParams(); const router = useRouter(); const id = String(params.id)
  const [project, setProject] = useState<Project | null>(null); const [proposals, setProposals] = useState<Proposal[]>([]); const [userId, setUserId] = useState(''); const [role, setRole] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { async function load() { const { data:{user} } = await supabase.auth.getUser(); if (!user) { router.replace('/login'); return }; setUserId(user.id); const {data:p} = await supabase.from('profiles').select('role').eq('id',user.id).single(); setRole(p?.role || ''); const {data:proj,error:pe} = await supabase.from('projects').select('id,client_id,title,description,budget_min,budget_max,deadline').eq('id',id).single(); if(pe){setError(pe.message);setLoading(false);return} setProject(proj); const {data:ps} = await supabase.from('proposals').select('id,freelancer_id,cover_letter,bid_amount,delivery_days,status,created_at').eq('project_id',id).order('created_at',{ascending:false}); if(ps?.length){const ids=ps.map(x=>x.freelancer_id); const {data:people}=await supabase.from('profiles').select('id,full_name').in('id',ids); const map=Object.fromEntries((people??[]).map(x=>[x.id,x])); setProposals(ps.map(x=>({...x,profile:map[x.freelancer_id]||null})))} else setProposals([]); setLoading(false) } load() },[id,router])
  async function accept(p: Proposal) { if (!project || project.client_id !== userId) return; const {error:e}=await supabase.from('proposals').update({status:'accepted'}).eq('id',p.id); if(e){setError(e.message);return} const {error:oe}=await supabase.from('orders').insert({client_id:userId,freelancer_id:p.freelancer_id,project_id:project.id,amount_pkr:p.bid_amount,status:'pending',requirements:project.description || ''}); if(oe){setError(oe.message);return} setProposals(xs=>xs.map(x=>x.id===p.id?{...x,status:'accepted'}:x)) }
  async function reject(p: Proposal) { const {error:e}=await supabase.from('proposals').update({status:'rejected'}).eq('id',p.id); if(!e)setProposals(xs=>xs.map(x=>x.id===p.id?{...x,status:'rejected'}:x)); else setError(e.message) }
  if(loading)return <main className="section"><div className="container"><p>Loading project...</p></div></main>
  if(!project)return <main className="section"><div className="container"><div className="card"><h2>Project not found</h2><p className="muted">{error}</p><Link className="btn" href="/work">Back</Link></div></div></main>
  const owner = project.client_id===userId
  return <main className="section"><div className="container"><span className="pill">Project</span><h1>{project.title}</h1><p className="muted">{project.description || 'No description provided.'}</p><p><b>Budget:</b> PKR {Number(project.budget_min??0).toLocaleString()}–{Number(project.budget_max??project.budget_min??0).toLocaleString()}{project.deadline ? ` · Deadline ${new Date(project.deadline).toLocaleDateString()}` : ''}</p>{error&&<p role="alert">{error}</p>}<div className="sectionhead" style={{marginTop:32}}><h2>Proposals ({proposals.length})</h2>{!owner && role==='freelancer'&&<Link className="btn primary" href={`/proposals?project=${id}`}>Submit proposal</Link>}</div>{proposals.length===0?<div className="card"><p className="muted">No proposals yet.</p></div>:<div className="grid">{proposals.map(p=><div className="card" key={p.id}><span className="pill">{p.status}</span><h3>{p.profile?.full_name||'Freelancer'}</h3><p>{p.cover_letter}</p><p><b>PKR {Number(p.bid_amount).toLocaleString()}</b> · {p.delivery_days} days</p><p className="muted">Submitted {new Date(p.created_at).toLocaleDateString()}</p>{owner&&p.status==='pending'&&<div style={{display:'flex',gap:10}}><button className="btn primary" onClick={()=>accept(p)}>Accept & create order</button><button className="btn" onClick={()=>reject(p)}>Reject</button></div>}</div>)}</div>}</div></main>
}
