'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Project = { id: string; client_id: string; title: string; description: string | null; budget_min: number | null; budget_max: number | null; deadline: string | null }
type Proposal = { id: string; freelancer_id: string; cover_letter: string; bid_amount: number; delivery_days: number; status: string; created_at: string; profile?: { full_name: string | null } | null }

export default function ProjectDetails() {
  const params = useParams(); const router = useRouter(); const id = String(params.id)
  const [project, setProject] = useState<Project | null>(null); const [proposals, setProposals] = useState<Proposal[]>([]); const [userId, setUserId] = useState(''); const [role, setRole] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [accepting, setAccepting] = useState(''); const [rejecting, setRejecting] = useState('')
  useEffect(() => { let mounted=true; async function load() { const { data:{user} } = await supabase.auth.getUser(); if (!user) { router.replace('/login'); return }; if(!mounted)return; setUserId(user.id); const {data:p} = await supabase.from('profiles').select('role').eq('id',user.id).single(); if(!mounted)return; setRole(p?.role || ''); const {data:proj,error:pe} = await supabase.from('projects').select('id,client_id,title,description,budget_min,budget_max,deadline').eq('id',id).single(); if(pe){if(mounted){setError(pe.message);setLoading(false)}return} if(!mounted)return; setProject(proj); const {data:ps,error:proposalsError} = await supabase.from('proposals').select('id,freelancer_id,cover_letter,bid_amount,delivery_days,status,created_at').eq('project_id',id).order('created_at',{ascending:false}); if(proposalsError){if(mounted){setError(proposalsError.message);setLoading(false)}return} if(ps?.length){const ids=ps.map(x=>x.freelancer_id); const {data:people}=await supabase.from('profiles').select('id,full_name').in('id',ids); if(mounted){const map=Object.fromEntries((people??[]).map(x=>[x.id,x]));setProposals(ps.map(x=>({...x,profile:map[x.freelancer_id]||null})))}} else if(mounted)setProposals([]); if(mounted)setLoading(false) } load(); return()=>{mounted=false} },[id,router])
  async function accept(p: Proposal) { if (!project || project.client_id !== userId || accepting || rejecting) return; setError(''); setAccepting(p.id); const {data:orderId,error:e}=await supabase.rpc('accept_proposal',{p_proposal_id:p.id}); if(e){setError(e.message);setAccepting('');return} setProposals(xs=>xs.map(x=>x.status==='pending'?{...x,status:x.id===p.id?'accepted':'rejected'}:x)); setAccepting(''); if(typeof orderId==='string'&&orderId) router.push(`/orders/${orderId}`) }
  async function reject(p: Proposal) { if (!project || project.client_id !== userId || accepting || rejecting) return; setError(''); setRejecting(p.id); const {error:e}=await supabase.rpc('reject_proposal',{p_proposal_id:p.id}); if(!e)setProposals(xs=>xs.map(x=>x.id===p.id?{...x,status:'rejected'}:x)); else setError(e.message); setRejecting('') }
  if(loading)return <main className="section"><div className="container"><div className="card" role="status"><p>Loading project...</p></div></div></main>
  if(!project)return <main className="section"><div className="container"><div className="card"><h2>Project not found</h2><p className="muted">{error||'This project may have been removed or is unavailable.'}</p><Link className="btn" href="/work">Back to work</Link></div></div></main>
  const owner = project.client_id===userId
  return <main className="section"><div className="container"><span className="pill">Project</span><h1>{project.title}</h1><p className="muted" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{project.description || 'No description provided.'}</p><p><b>Budget:</b> PKR {Number(project.budget_min??0).toLocaleString()}–{Number(project.budget_max??project.budget_min??0).toLocaleString()}{project.deadline ? ` · Deadline ${new Date(project.deadline).toLocaleDateString()}` : ''}</p>{error&&<div className="card" role="alert" style={{marginTop:16}}><p>{error}</p></div>}<div className="sectionhead" style={{marginTop:32}}><div><h2>Proposals ({proposals.length})</h2><p className="muted">Review bids, delivery times and freelancer messages.</p></div>{!owner && role==='freelancer'&&<Link className="btn primary" href={`/proposals?project=${id}`}>Submit proposal</Link>}</div>{proposals.length===0?<div className="card"><p className="muted">No proposals yet. Freelancers can submit one when they are ready.</p></div>:<div className="grid">{proposals.map(p=>{const busy=accepting===p.id||rejecting===p.id;return <div className="card" key={p.id}><span className="pill">{p.status.replaceAll('_',' ')}</span><h3>{p.profile?.full_name||'Freelancer'}</h3><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{p.cover_letter}</p><p><b>PKR {Number(p.bid_amount).toLocaleString()}</b> · {p.delivery_days} days</p><p className="muted">Submitted {new Date(p.created_at).toLocaleDateString()}</p>{owner&&p.status==='pending'&&<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button type="button" className="btn primary" disabled={!!accepting||!!rejecting} onClick={()=>accept(p)} aria-busy={busy}>{accepting===p.id?'Creating order...':'Accept & create order'}</button><button type="button" className="btn" disabled={!!accepting||!!rejecting} onClick={()=>reject(p)} aria-busy={busy}>{rejecting===p.id?'Rejecting...':'Reject'}</button></div>}</div>})}</div>}</div></main>
}
