'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Profile={id:string;full_name:string;username:string|null;bio:string|null;location:string|null;verified:boolean;role:string;avatar_url:string|null}
type Service={id:string;title:string;description:string;price_pkr:number;delivery_days:number;rating:number;review_count:number}
type Review={rating:number;comment:string|null;created_at:string;reviewer:{full_name:string|null}|null}

export default function FreelancerProfile(){const {username}=useParams();const [profile,setProfile]=useState<Profile|null>(null);const [services,setServices]=useState<Service[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [loading,setLoading]=useState(true)
useEffect(()=>{async function load(){const key=String(username);let {data:p}=await supabase.from('profiles').select('id,full_name,username,bio,location,verified,role,avatar_url').eq('username',key).eq('role','freelancer').maybeSingle();if(!p){const r=await supabase.from('profiles').select('id,full_name,username,bio,location,verified,role,avatar_url').eq('id',key).eq('role','freelancer').maybeSingle();p=r.data}if(!p){setLoading(false);return}setProfile(p);const [{data:s},{data:r}]=await Promise.all([supabase.from('services').select('id,title,description,price_pkr,delivery_days,rating,review_count').eq('freelancer_id',p.id).eq('published',true).order('created_at',{ascending:false}),supabase.from('reviews').select('rating,comment,created_at,reviewer:profiles!reviews_reviewer_id_fkey(full_name)').eq('reviewee_id',p.id).order('created_at',{ascending:false}).limit(10)]);setServices(s??[]);setReviews((r??[]) as Review[]);setLoading(false)}load()},[username])
if(loading)return <main className="section"><div className="container"><p>Loading profile...</p></div></main>
if(!profile)return <main className="section"><div className="container"><div className="card"><h2>Freelancer not found</h2><Link className="btn" href="/talent">Back to talent</Link></div></div></main>
const average=reviews.length?reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length:null
return <main className="section"><div className="container"><div className="profile-card card" style={{display:'flex',gap:20,alignItems:'center',flexWrap:'wrap'}}>{profile.avatar_url?<img src={profile.avatar_url} alt={profile.full_name} className="avatar-large" style={{width:110,height:110,objectFit:'cover',borderRadius:'50%'}}/>:<div className="avatar-large" style={{width:110,height:110,borderRadius:'50%',display:'grid',placeItems:'center',fontSize:40,fontWeight:700}}>{profile.full_name.charAt(0).toUpperCase()}</div>}<div style={{flex:1,minWidth:220}}><span className="pill">{profile.verified?'✓ Verified freelancer':'HUNAR freelancer'}</span><h1 style={{marginBottom:6}}>{profile.full_name}</h1><p className="muted">{profile.location||'Pakistan'} · @{profile.username||profile.id.slice(0,8)}</p>{reviews.length>0&&<p style={{marginTop:10}}><b>★ {average?.toFixed(1)}</b> · {reviews.length} recent reviews</p>}</div><Link className="btn" href="/talent">Browse talent</Link></div><p style={{maxWidth:760,marginTop:24}}>{profile.bio||'Professional freelancer ready to help with your project.'}</p><div className="sectionhead" style={{marginTop:36}}><div><h2>Services</h2><p className="muted">Choose a service and place an order.</p></div></div><div className="grid">{services.length===0?<div className="card"><h3>No published services</h3><p className="muted">This freelancer has not published a service yet.</p></div>:services.map(s=><div className="card" key={s.id}><span className="pill">★ {Number(s.rating).toFixed(1)} · {s.review_count} reviews</span><h3>{s.title}</h3><p className="muted">{s.description||'Professional freelance service.'}</p><div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap',marginTop:16}}><div><b>PKR {Number(s.price_pkr).toLocaleString()}</b><span className="muted"> · {s.delivery_days} day delivery</span></div><Link className="btn primary" href={`/checkout?service=${s.id}`}>Order now</Link></div></div>)}</div><div style={{marginTop:42}}><div className="sectionhead"><div><h2>Recent reviews</h2><p className="muted">Feedback from HUNAR clients.</p></div></div>{reviews.length===0?<div className="card"><p className="muted">No reviews yet. Complete orders will appear here after clients leave feedback.</p></div>:<div className="grid">{reviews.map((r,i)=><div className="card" key={`${r.created_at}-${i}`}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><b>★ {r.rating}/5</b><span className="muted">{new Date(r.created_at).toLocaleDateString()}</span></div><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{r.comment||'Great experience.'}</p><p className="muted">{r.reviewer?.full_name||'HUNAR client'}</p></div>)}</div>}</div></div></main>}
