'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Profile={id:string;full_name:string;username:string|null;bio:string|null;location:string|null;verified:boolean;role:string}
type Service={id:string;title:string;description:string;price_pkr:number;delivery_days:number;rating:number;review_count:number}
type Review={rating:number;comment:string|null;created_at:string;reviewer:{full_name:string|null}|null}

export default function FreelancerProfile(){const {username}=useParams();const [profile,setProfile]=useState<Profile|null>(null);const [services,setServices]=useState<Service[]>([]);const [reviews,setReviews]=useState<Review[]>([]);const [loading,setLoading]=useState(true)
useEffect(()=>{async function load(){const key=String(username);let {data:p}=await supabase.from('profiles').select('id,full_name,username,bio,location,verified,role').eq('username',key).eq('role','freelancer').maybeSingle();if(!p){const r=await supabase.from('profiles').select('id,full_name,username,bio,location,verified,role').eq('id',key).eq('role','freelancer').maybeSingle();p=r.data}if(!p){setLoading(false);return}setProfile(p);const [{data:s},{data:r}]=await Promise.all([supabase.from('services').select('id,title,description,price_pkr,delivery_days,rating,review_count').eq('freelancer_id',p.id).eq('published',true).order('created_at',{ascending:false}),supabase.from('reviews').select('rating,comment,created_at,reviewer:profiles!reviews_reviewer_id_fkey(full_name)').eq('reviewee_id',p.id).order('created_at',{ascending:false}).limit(10)]);setServices(s??[]);setReviews((r??[]) as Review[]);setLoading(false)}load()},[username])
if(loading)return <main className="section"><div className="container"><p>Loading profile...</p></div></main>
if(!profile)return <main className="section"><div className="container"><div className="card"><h2>Freelancer not found</h2><Link className="btn" href="/talent">Back to talent</Link></div></div></main>
return <main className="section"><div className="container"><span className="pill">{profile.verified?'✓ Verified freelancer':'HUNAR freelancer'}</span><h1>{profile.full_name}</h1><p className="muted">{profile.location||'Pakistan'} · @{profile.username||profile.id.slice(0,8)}</p><p style={{maxWidth:760}}>{profile.bio||'Professional freelancer ready to help with your project.'}</p><div className="sectionhead" style={{marginTop:36}}><div><h2>Services</h2><p className="muted">Choose a service and place your order.</p></div><Link className="btn" href="/talent">All talent</Link></div><div className="grid">{services.length===0?<div className="card"><h3>No published services</h3><p className="muted">This freelancer has not published a service yet.</p></div>:services.map(s=><div className="card" key={s.id}><span className="pill">★ {Number(s.rating).toFixed(1)} · {s.review_count} reviews</span><h3>{s.title}</h3><p className="muted">{s.description||'Professional freelance service.'}</p><p><b>PKR {Number(s.price_pkr).toLocaleString()}</b> · {s.delivery_days} day delivery</p><Link className="btn primary" href={`/checkout?service=${s.id}`}>Order now</Link></div>)}</div><div style={{marginTop:42}}><h2>Recent reviews</h2>{reviews.length===0?<p className="muted">No reviews yet.</p>:<div className="grid">{reviews.map((r,i)=><div className="card" key={i}><b>★ {r.rating}/5</b><p>{r.comment||'Great experience.'}</p><p className="muted">{r.reviewer?.full_name||'HUNAR client'} · {new Date(r.created_at).toLocaleDateString()}</p></div>)}</div>}</div></div></main>}
